<?php

/*
 * This document has been generated with
 * https://mlocati.github.io/php-cs-fixer-configurator/#version:3.49.0|configurator
 * you can change this configuration by importing this file.
 */
$config = new PhpCsFixer\Config();

return $config
    ->setRiskyAllowed(true)
    ->setParallelConfig(PhpCsFixer\Runner\Parallel\ParallelConfigFactory::detect())
    ->setRules([
        '@PHPUnit100Migration:risky' => true,
        '@PER-CS2.0:risky'           => true,
        '@PER-CS2.0'                 => true,
        '@PHP83Migration'            => true,
        '@PHP80Migration:risky'      => true,

        // Exceptions to rule sets
        'binary_operator_spaces'   => ['operators' => ['=' => 'single_space', '=>' => 'align_single_space_minimal']],
        'cast_spaces'              => ['space' => 'none'],
        'declare_strict_types'     => false,
        'ordered_imports'          => ['sort_algorithm' => 'alpha', 'imports_order' => ['class', 'function', 'const']],
        'pow_to_exponentiation'    => false,
        'control_structure_braces' => false,

        // Additional rules
        'array_indentation'                                => true,
        'array_push'                                       => true,
        'backtick_to_shell_exec'                           => true,
        'blank_line_before_statement'                      => ['statements' => ['continue', 'declare', 'return', 'throw', 'try']],
        'class_attributes_separation'                      => ['elements' => ['method' => 'one']],
        'class_reference_name_casing'                      => true,
        'combine_consecutive_issets'                       => true,
        'combine_consecutive_unsets'                       => true,
        'comment_to_phpdoc'                                => true,
        'date_time_create_from_format_call'                => true,
        'declare_parentheses'                              => true,
        'dir_constant'                                     => true,
        'empty_loop_body'                                  => true,
        'empty_loop_condition'                             => true,
        'ereg_to_preg'                                     => true,
        'explicit_indirect_variable'                       => true,
        'explicit_string_variable'                         => true,
        'fopen_flag_order'                                 => true,
        'fopen_flags'                                      => true,
        'fully_qualified_strict_types'                     => true,
        'function_to_constant'                             => true,
        'general_phpdoc_annotation_remove'                 => true,
        'global_namespace_import'                          => true,
        'heredoc_closing_marker'                           => true,
        'heredoc_to_nowdoc'                                => true,
        'include'                                          => true,
        'increment_style'                                  => ['style' => 'post'],
        'integer_literal_case'                             => true,
        'is_null'                                          => true,
        'lambda_not_used_import'                           => true,
        'linebreak_after_opening_tag'                      => true,
        'logical_operators'                                => true,
        'long_to_shorthand_operator'                       => true,
        'magic_constant_casing'                            => true,
        'magic_method_casing'                              => true,
        'mb_str_functions'                                 => true,
        'method_chaining_indentation'                      => true,
        'modernize_types_casting'                          => true,
        'multiline_comment_opening_closing'                => true,
        'multiline_whitespace_before_semicolons'           => true,
        'native_function_casing'                           => true,
        'native_type_declaration_casing'                   => true,
        'no_alias_language_construct_call'                 => true,
        'no_alternative_syntax'                            => true,
        'no_blank_lines_after_phpdoc'                      => true,
        'no_empty_comment'                                 => true,
        'no_empty_phpdoc'                                  => true,
        'no_empty_statement'                               => true,
        'no_extra_blank_lines'                             => true,
        'no_leading_namespace_whitespace'                  => true,
        'no_multiline_whitespace_around_double_arrow'      => true,
        'no_null_property_initialization'                  => true,
        'no_short_bool_cast'                               => true,
        'no_singleline_whitespace_before_semicolons'       => true,
        'no_spaces_around_offset'                          => true,
        'no_superfluous_elseif'                            => true,
        'no_superfluous_phpdoc_tags'                       => true,
        'no_trailing_comma_in_singleline'                  => true,
        'no_unneeded_braces'                               => true,
        'no_unneeded_control_parentheses'                  => true,
        'no_unused_imports'                                => true,
        'no_useless_else'                                  => true,
        'no_useless_return'                                => true,
        'no_useless_sprintf'                               => true,
        'nullable_type_declaration'                        => true,
        'nullable_type_declaration_for_default_null_value' => true,
        'object_operator_without_whitespace'               => true,
        'operator_linebreak'                               => true,
        'ordered_interfaces'                               => true,
        'ordered_traits'                                   => true,
        'ordered_types'                                    => true,
        'php_unit_construct'                               => true,
        'php_unit_method_casing'                           => true,
        'php_unit_set_up_tear_down_visibility'             => true,
        'php_unit_strict'                                  => true,
        'php_unit_test_annotation'                         => true,
        'php_unit_test_case_static_method_calls'           => true,
        'phpdoc_align'                                     => true,
        'phpdoc_annotation_without_dot'                    => true,
        'phpdoc_indent'                                    => true,
        'phpdoc_inline_tag_normalizer'                     => true,
        'phpdoc_line_span'                                 => ['const' => 'single', 'property' => 'single'],
        'phpdoc_no_access'                                 => true,
        'phpdoc_no_alias_tag'                              => true,
        'phpdoc_no_package'                                => true,
        'phpdoc_no_useless_inheritdoc'                     => true,
        'phpdoc_order'                                     => true,
        'phpdoc_order_by_value'                            => true,
        'phpdoc_param_order'                               => true,
        'phpdoc_return_self_reference'                     => true,
        'phpdoc_scalar'                                    => true,
        'phpdoc_separation'                                => true,
        'phpdoc_single_line_var_spacing'                   => true,
        'phpdoc_summary'                                   => true,
        'phpdoc_tag_casing'                                => true,
        'phpdoc_tag_type'                                  => true,
        'phpdoc_to_comment'                                => true,
        'phpdoc_trim'                                      => true,
        'phpdoc_trim_consecutive_blank_line_separation'    => true,
        'phpdoc_types'                                     => true,
        'phpdoc_types_order'                               => true,
        'phpdoc_var_annotation_correct_order'              => true,
        'phpdoc_var_without_name'                          => true,
        'regular_callable_call'                            => true,
        'return_assignment'                                => true,
        'self_accessor'                                    => true,
        'self_static_accessor'                             => true,
        'semicolon_after_instruction'                      => true,
        'set_type_to_cast'                                 => true,
        'simplified_if_return'                             => true,
        'single_line_comment_spacing'                      => true,
        'single_line_comment_style'                        => true,
        'single_quote'                                     => true,
        'single_space_around_construct'                    => true,
        'space_after_semicolon'                            => true,
        'standardize_increment'                            => true,
        'standardize_not_equals'                           => true,
        'strict_comparison'                                => true,
        'strict_param'                                     => true,
        'string_implicit_backslashes'                      => true,
        'string_length_to_empty'                           => true,
        'string_line_ending'                               => true,
        'switch_continue_to_break'                         => true,
        'ternary_to_elvis_operator'                        => true,
        'trim_array_spaces'                                => true,
        'type_declaration_spaces'                          => true,
        'types_spaces'                                     => true,
        'whitespace_after_comma_in_array'                  => true,
        'multiline_promoted_properties'                    => true,
    ])
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->in(__DIR__)
            ->exclude([
                'vendor',
            ])
    );
